### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Cannot modify resource set without a write transaction

### ISSUE THREAD

**Issue by NicolasRouquette** [JPL-IMCE/gov.nasa.jpl.imce.oml#114]
Launch the [OML Product](https://github.com/JPL-IMCE/gov.nasa.jpl.imce.oml/blob/master/releng/gov.nasa.jpl.imce.oml.product/gov.nasa.jpl.imce.oml.rcp.product)

If the runtime workspace contains the [IMCE Ontologies project](https://github.com/JPL-IMCE/gov.nasa.jpl.imce.ontologies.public), then:

1) Switch to the "Sirius" perspective.
2) This should trigger some activity and eventually result in the following error:

> An internal error occurred during: "Loading models".
The modeling project "gov.nasa.jpl.imce.ontologies.public" is invalid: Problem during loading models: Cannot modify resource set without a write transaction

```
!SESSION 2017-09-20 09:57:58.112 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_121
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product gov.nasa.jpl.imce.oml.rcp.product -clearPersistedState
Command-line arguments:  -product gov.nasa.jpl.imce.oml.rcp.product -data /opt/local/imce/tools/eclipse.neon3/workspace.neon3/../runtime-gov.nasa.jpl.imce.oml.rcp.product(1) -dev file:/opt/local/imce/tools/eclipse.neon3/workspace.neon3/.metadata/.plugins/org.eclipse.pde.core/gov.nasa.jpl.imce.oml.rcp.product (1)/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog -clearPersistedState

!ENTRY org.eclipse.core.net 1 0 2017-09-20 09:58:02.480
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences

!ENTRY org.eclipse.ui.navigator.resources 4 0 2017-09-20 09:58:13.858
!MESSAGE Could not acquire INavigatorContentService: Project Explorer not found.
Could not acquire INavigatorContentService: Project Explorer not found.
Reason:

!ENTRY org.eclipse.emf.transaction 4 41 2017-09-20 09:58:31.935
!MESSAGE Read-only transaction rolled back
!SUBENTRY 1 org.eclipse.emf.transaction 4 40 2017-09-20 09:58:31.935
!MESSAGE Transaction aborted due to concurrent write

!ENTRY org.eclipse.core.jobs 4 2 2017-09-20 09:58:31.953
!MESSAGE An internal error occurred during: "Loading models".
!STACK 0
java.lang.RuntimeException: The modeling project "gov.nasa.jpl.imce.ontologies.public" is invalid: Problem during loading models: Cannot modify resource set without a write transaction
	at org.eclipse.sirius.ui.tools.internal.views.common.modelingproject.OpenRepresentationsFileJob.runInWorkspace(OpenRepresentationsFileJob.java:136)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.IllegalStateException: Cannot modify resource set without a write transaction
	at org.eclipse.emf.transaction.impl.TransactionChangeRecorder.assertWriting(TransactionChangeRecorder.java:349)
	at org.eclipse.emf.transaction.impl.TransactionChangeRecorder.appendNotification(TransactionChangeRecorder.java:303)
	at org.eclipse.emf.transaction.impl.TransactionChangeRecorder.processObjectNotification(TransactionChangeRecorder.java:285)
	at org.eclipse.emf.transaction.impl.TransactionChangeRecorder.notifyChanged(TransactionChangeRecorder.java:241)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.xsd.impl.XSDConcreteComponentImpl.eNotify(XSDConcreteComponentImpl.java:1153)
	at org.eclipse.emf.ecore.util.EcoreEList.dispatchNotification(EcoreEList.java:249)
	at org.eclipse.emf.common.notify.impl.NotifyingListImpl.addUnique(NotifyingListImpl.java:304)
	at org.eclipse.emf.common.util.AbstractEList.add(AbstractEList.java:303)
	at org.eclipse.xsd.impl.XSDSchemaImpl.imported(XSDSchemaImpl.java:3120)
	at org.eclipse.xsd.impl.XSDImportImpl.handleResolvedSchema(XSDImportImpl.java:430)
	at org.eclipse.xsd.impl.XSDSchemaDirectiveImpl.resolve(XSDSchemaDirectiveImpl.java:393)
	at org.eclipse.xsd.impl.XSDImportImpl.importSchema(XSDImportImpl.java:416)
	at org.eclipse.xsd.impl.XSDSchemaImpl.resolveSchema(XSDSchemaImpl.java:2247)
	at org.eclipse.xsd.impl.XSDSchemaImpl.resolveNamedComponent(XSDSchemaImpl.java:2280)
	at org.eclipse.xsd.impl.XSDSchemaImpl.resolveAttributeDeclaration(XSDSchemaImpl.java:2302)
	at org.eclipse.xsd.impl.XSDConcreteComponentImpl.resolveAttributeDeclaration(XSDConcreteComponentImpl.java:2438)
	at org.eclipse.xsd.impl.XSDAttributeDeclarationImpl.patch(XSDAttributeDeclarationImpl.java:196)
	at org.eclipse.xsd.impl.XSDConcreteComponentImpl.patch(XSDConcreteComponentImpl.java:529)
	at org.eclipse.xsd.impl.XSDAttributeUseImpl.patch(XSDAttributeUseImpl.java:761)
	at org.eclipse.xsd.impl.XSDConcreteComponentImpl.patch(XSDConcreteComponentImpl.java:529)
	at org.eclipse.xsd.impl.XSDNamedComponentImpl.patch(XSDNamedComponentImpl.java:779)
	at org.eclipse.xsd.impl.XSDTypeDefinitionImpl.patch(XSDTypeDefinitionImpl.java:241)
	at org.eclipse.xsd.impl.XSDComplexTypeDefinitionImpl.patch(XSDComplexTypeDefinitionImpl.java:1049)
	at org.eclipse.xsd.impl.XSDConcreteComponentImpl.patch(XSDConcreteComponentImpl.java:529)
	at org.eclipse.xsd.impl.XSDNamedComponentImpl.patch(XSDNamedComponentImpl.java:779)
	at org.eclipse.xsd.impl.XSDElementDeclarationImpl.patch(XSDElementDeclarationImpl.java:542)
	at org.eclipse.xsd.impl.XSDConcreteComponentImpl.patch(XSDConcreteComponentImpl.java:529)
	at org.eclipse.xsd.impl.XSDSchemaImpl.patch(XSDSchemaImpl.java:1596)
	at org.eclipse.xsd.impl.XSDSchemaImpl.changeAttribute(XSDSchemaImpl.java:2457)
	at org.eclipse.xsd.impl.XSDConcreteComponentImpl.eNotify(XSDConcreteComponentImpl.java:1148)
	at org.eclipse.xsd.impl.XSDSchemaImpl.setSchemaLocation(XSDSchemaImpl.java:887)
	at org.eclipse.xsd.util.XSDResourceImpl.doLoad(XSDResourceImpl.java:757)
	at org.eclipse.xsd.util.XSDResourceImpl.doLoad(XSDResourceImpl.java:790)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1518)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1297)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$ResourceLocator.demandLoadHelper(ResourceSetImpl.java:804)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$MappedResourceLocator.getResource(ResourceSetImpl.java:1204)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:352)
	at org.eclipse.sirius.ecore.extender.tool.api.ModelUtils.getResource(ModelUtils.java:312)
	at org.eclipse.sirius.business.internal.session.danalysis.SemanticResourceGetter.collectTopLevelSemanticResources(SemanticResourceGetter.java:50)
	at org.eclipse.sirius.business.internal.session.danalysis.SessionResourcesTracker$1.run(SessionResourcesTracker.java:145)
	at org.eclipse.emf.transaction.impl.TransactionalEditingDomainImpl.runExclusive(TransactionalEditingDomainImpl.java:328)
	at org.eclipse.emf.transaction.util.TransactionUtil.runExclusive(TransactionUtil.java:328)
	at org.eclipse.sirius.business.internal.session.danalysis.SessionResourcesTracker.getSemanticResources(SessionResourcesTracker.java:149)
	at org.eclipse.sirius.business.internal.session.danalysis.DAnalysisSessionImpl.getSemanticResources(DAnalysisSessionImpl.java:664)
	at org.eclipse.sirius.business.internal.session.danalysis.DAnalysisSessionImpl.disableAndRemoveECrossReferenceAdapters(DAnalysisSessionImpl.java:311)
	at org.eclipse.sirius.business.internal.session.danalysis.DAnalysisSessionImpl.close(DAnalysisSessionImpl.java:1250)
	at org.eclipse.sirius.business.internal.session.danalysis.DAnalysisSessionImpl.open(DAnalysisSessionImpl.java:1201)
	at org.eclipse.sirius.business.internal.session.SessionManagerImpl.openSession(SessionManagerImpl.java:390)
	at org.eclipse.sirius.ui.tools.internal.views.common.modelingproject.OpenRepresentationsFileJob.performOpenSession(OpenRepresentationsFileJob.java:157)
	at org.eclipse.sirius.ui.tools.internal.views.common.modelingproject.OpenRepresentationsFileJob.runInWorkspace(OpenRepresentationsFileJob.java:126)
	... 2 more
```

It is possible that this behavior depends on how Eclipse is "initialized".
For example, this behavior may be different if, e.g., one opens the "Modeling Perspective" before opening the "Sirius" perspective, then the modeling perspective will trigger OML validation without any of the Sirius related behavior.

**Comment by NicolasRouquette** [comment]
This seems to be the same problem as this bug:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=513407

See my comment here: 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=513407#c7

The bad news is that the workaround to this problem seems to cause regression problems in Sirius 5.1

**Comment by NicolasRouquette** [comment]
Launching the OML WB w/ debug breakpoints on java.lang.IllegalStateException helped track down the cause of the problem to loading *.xsd files -- in particular: 

https://github.com/JPL-IMCE/gov.nasa.jpl.imce.ontologies.public/blob/master/ontologies/www.w3.org/2001/XMLSchema.xsd

Removing this file from the project and restarting with "-clean" suffices to avoid the problem.

Bottom line: The Eclipse XSD is currently architecturally incompatible with Sirius-based viewpoint/diagram modeling.
