### ISSUE TITLE
Cannot use UUIDs as IDs of elements

### ISSUE THREAD

**Issue by sjiherzig** [JPL-IMCE/gov.nasa.jpl.imce.oml#126]
_**Note:** I am using 0.8.0.0-M26, since I am unable to update due to a non-functioning update site / bintray access issues. Please feel free to close if this is a known bug that has already been addressed in later versions._

Serializing an OML model fails when using UUIDs as IDs / string values (e.g., here, to use a UUID as a name / identifier for a ConceptInstance). The following exception is thrown:

```
java.lang.RuntimeException: Error while converting value '81574965-9c4a-4f91-8a10-7adb458e18bd' for grammar rule 'ID' to string via ValueConverter.
Semantic Object: Extent.modules[0]->DescriptionBox.conceptInstances[1]->ConceptInstance'81574965-9c4a-4f91-8a10-7adb458e18bd'
URI: ontologies/caesar.examples/simple/CaesarSimpleSpacecraft.uml.oml
EStructuralFeature: omld::ConceptualEntitySingletonInstance.name
	at org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic$ExceptionThrowingAcceptor.accept(ISerializationDiagnostic.java:129)
	at org.eclipse.xtext.serializer.tokens.ValueSerializer.serializeAssignedValue(ValueSerializer.java:82)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.getToken(SequenceFeeder.java:489)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.accept(SequenceFeeder.java:244)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.accept(BacktrackingSemanticSequencer.java:441)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.createSequence(BacktrackingSemanticSequencer.java:501)
	at gov.nasa.jpl.imce.oml.dsl.serializer.OMLSemanticSequencer.sequence_ConceptInstance(OMLSemanticSequencer.java:488)
	at gov.nasa.jpl.imce.oml.dsl.serializer.OMLSemanticSequencer.sequence(OMLSemanticSequencer.java:172)
	at org.eclipse.xtext.serializer.sequencer.AbstractSemanticSequencer.createSequence(AbstractSemanticSequencer.java:67)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.acceptEObjectRuleCall(SequenceFeeder.java:325)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.acceptRuleCall(SequenceFeeder.java:352)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.accept(SequenceFeeder.java:263)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.accept(BacktrackingSemanticSequencer.java:434)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.createSequence(BacktrackingSemanticSequencer.java:501)
	at gov.nasa.jpl.imce.oml.dsl.serializer.OMLSemanticSequencer.sequence_DescriptionBox(OMLSemanticSequencer.java:570)
	at gov.nasa.jpl.imce.oml.dsl.serializer.OMLSemanticSequencer.sequence(OMLSemanticSequencer.java:175)
	at org.eclipse.xtext.serializer.sequencer.AbstractSemanticSequencer.createSequence(AbstractSemanticSequencer.java:67)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.acceptEObjectRuleCall(SequenceFeeder.java:325)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.acceptRuleCall(SequenceFeeder.java:352)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.accept(SequenceFeeder.java:263)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.accept(BacktrackingSemanticSequencer.java:434)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.createSequence(BacktrackingSemanticSequencer.java:501)
	at gov.nasa.jpl.imce.oml.dsl.serializer.OMLSemanticSequencer.sequence_Extent(OMLSemanticSequencer.java:732)
	at gov.nasa.jpl.imce.oml.dsl.serializer.OMLSemanticSequencer.sequence(OMLSemanticSequencer.java:139)
	at org.eclipse.xtext.serializer.sequencer.AbstractSemanticSequencer.createSequence(AbstractSemanticSequencer.java:67)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:115)
	at org.eclipse.xtext.serializer.impl.Serializer.serializeToRegions(Serializer.java:136)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:142)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:189)
	at org.eclipse.xtext.resource.XtextResource.doSave(XtextResource.java:386)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.save(ResourceImpl.java:1430)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.save(ResourceImpl.java:999)
	at gov.nasa.jpl.caesar.adapters.mapping.uml.mdoml.util.OMLUtilities.saveOMLModel(OMLUtilities.java:92)
	at gov.nasa.jpl.caesar.adapters.mapping.uml.mdoml.mappings.MDUMLviaOpenAPI2OMLTransformation.main(MDUMLviaOpenAPI2OMLTransformation.java:418)
Caused by: java.lang.NullPointerException
	at org.eclipse.xtext.parser.antlr.TokenTool.getLexerRuleName(TokenTool.java:66)
	at org.eclipse.xtext.conversion.impl.AbstractLexerBasedConverter.getRuleName(AbstractLexerBasedConverter.java:116)
	at org.eclipse.xtext.conversion.impl.AbstractLexerBasedConverter.assertTokens(AbstractLexerBasedConverter.java:68)
	at org.eclipse.xtext.conversion.impl.AbstractLexerBasedConverter.assertTokens(AbstractLexerBasedConverter.java:58)
	at org.eclipse.xtext.conversion.impl.AbstractLexerBasedConverter.toString(AbstractLexerBasedConverter.java:49)
	at gov.nasa.jpl.imce.oml.dsl.util.OMLValueConverterService.toString(OMLValueConverterService.java:195)
	at org.eclipse.xtext.serializer.tokens.ValueSerializer.serializeAssignedValue(ValueSerializer.java:74)
	... 32 more
```

When adding a prefix such as `ID_`, parsing works perfectly fine. I.e., the following does **not** work:

```oml
conceptInstance(817215c5-4b7f-43ed-a60e-8b1bcbd7cd78 is-a UML-metamodel:Component)
```

The following, however, ***does*** work:

```oml
conceptInstance(ID_817215c5-4b7f-43ed-a60e-8b1bcbd7cd78 is-a UML-metamodel:Component)
```

Could this be due to the value being parsed as a `LiteralUUID` rather than a `STRING / ID`?

**Comment by NicolasRouquette** [comment]
There are a couple of problems here.

1) https://bintray.com/jpl-imce is currently down.

This is an unfortunate miscommunication w/ bintray when I tried to do a "trial" for their premium subscription service. At the end of this "trial", bintray locked our organization. I'm in contact w/ bintray to resolve this problem.

2) Yes, the OML textual syntax for an ID is:

```
terminal fragment LETTER_DIGIT:		LETTER | DIGIT;

terminal fragment LETTER_DIGIT_PREFIX:	LETTER_DIGIT | '_';

terminal fragment LETTER_DIGIT_SUFFIX:	LETTER_DIGIT | '_' | '-' | '.';
	
terminal fragment ID_PREFIX: 			LETTER|'_';

terminal ID:							'^'? ID_PREFIX LETTER_DIGIT_SUFFIX*;
```

So, to use an actual UUID as an ID in OML, prefix it with a letter or an underscore as you've done.

Changing the grammar to allow the syntax of an UUID as an ID could lead to thorny lexical ambiguities. It may be worth experimenting at some point but that's not a high priority issue.

**Comment by sjiherzig** [comment]
Thanks! That makes sense.
