### ISSUE TITLE
Fix the OML grammar to allow a digit-leading character for an ID.

### ISSUE THREAD

**Issue by NicolasRouquette** [JPL-IMCE/gov.nasa.jpl.imce.oml#299]
Without this fix, there are problems constructing OML models with names like this:

```
OMLConverterFromOntologySyntax (Error while saving to OML): Error while converting value '2ASwitches10_zHdNhIFpEeiNqNyH9cEJTQ' for grammar rule 'ID' to string via ValueConverter.
Semantic Object: Extent.modules[0]->TerminologyGraph.boxStatements[0]->Concept'2ASwitches10_zHdNhIFpEeiNqNyH9cEJTQ'
URI: file:/opt/local/imce/users/nfr/github.caesar/europa.integration/target/conv.text/libraries.resources/europa.jpl.nasa.gov/efse/libraries/AssemblyTypes.oml
EStructuralFeature: omlt::Term.name
java.lang.RuntimeException: Error while converting value '2ASwitches10_zHdNhIFpEeiNqNyH9cEJTQ' for grammar rule 'ID' to string via ValueConverter.
Semantic Object: Extent.modules[0]->TerminologyGraph.boxStatements[0]->Concept'2ASwitches10_zHdNhIFpEeiNqNyH9cEJTQ'
URI: file:/opt/local/imce/users/nfr/github.caesar/europa.integration/target/conv.text/libraries.resources/europa.jpl.nasa.gov/efse/libraries/AssemblyTypes.oml
EStructuralFeature: omlt::Term.name

	at org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic$ExceptionThrowingAcceptor.accept(ISerializationDiagnostic.java:129)
	at org.eclipse.xtext.serializer.tokens.ValueSerializer.serializeAssignedValue(ValueSerializer.java:82)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.getToken(SequenceFeeder.java:489)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.accept(SequenceFeeder.java:244)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.accept(BacktrackingSemanticSequencer.java:441)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.createSequence(BacktrackingSemanticSequencer.java:501)
	at gov.nasa.jpl.imce.oml.dsl.serializer.OMLSemanticSequencer.sequence_Concept(OMLSemanticSequencer.java:660)
	at gov.nasa.jpl.imce.oml.dsl.serializer.OMLSemanticSequencer.sequence(OMLSemanticSequencer.java:259)
	at org.eclipse.xtext.serializer.sequencer.AbstractSemanticSequencer.createSequence(AbstractSemanticSequencer.java:67)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.acceptEObjectRuleCall(SequenceFeeder.java:325)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.acceptRuleCall(SequenceFeeder.java:352)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.accept(SequenceFeeder.java:263)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.accept(BacktrackingSemanticSequencer.java:434)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.createSequence(BacktrackingSemanticSequencer.java:501)
	at gov.nasa.jpl.imce.oml.dsl.serializer.OMLSemanticSequencer.sequence_TerminologyGraph(OMLSemanticSequencer.java:1624)
	at gov.nasa.jpl.imce.oml.dsl.serializer.OMLSemanticSequencer.sequence(OMLSemanticSequencer.java:229)
	at org.eclipse.xtext.serializer.sequencer.AbstractSemanticSequencer.createSequence(AbstractSemanticSequencer.java:67)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.acceptEObjectRuleCall(SequenceFeeder.java:325)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.acceptRuleCall(SequenceFeeder.java:352)
	at org.eclipse.xtext.serializer.acceptor.SequenceFeeder.accept(SequenceFeeder.java:263)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.accept(BacktrackingSemanticSequencer.java:434)
	at org.eclipse.xtext.serializer.sequencer.BacktrackingSemanticSequencer.createSequence(BacktrackingSemanticSequencer.java:501)
	at gov.nasa.jpl.imce.oml.dsl.serializer.OMLSemanticSequencer.sequence_Extent(OMLSemanticSequencer.java:876)
	at gov.nasa.jpl.imce.oml.dsl.serializer.OMLSemanticSequencer.sequence(OMLSemanticSequencer.java:151)
	at org.eclipse.xtext.serializer.sequencer.AbstractSemanticSequencer.createSequence(AbstractSemanticSequencer.java:67)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:115)
	at org.eclipse.xtext.serializer.impl.Serializer.serializeToRegions(Serializer.java:136)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:142)
	at org.eclipse.xtext.serializer.impl.Serializer.serialize(Serializer.java:189)
	at org.eclipse.xtext.resource.XtextResource.doSave(XtextResource.java:386)
```

**Comment by NicolasRouquette** [comment]
Need to relax the ID format requirements to allow arbitrary characters and convert an OML ID to a well-formed fragment via character encoding.
